# Specify the name of the device on which the playback should
# be started. Make sure that the device is online.
device:
  device_name: Spotijyd@raspberrypi

# Here, the settings concerning the lights have their place
light:
  led_count: 18  #  the number of LEDs that are on your strip
  led_brightness: 130  #  the brightness of your leds (max 255)
  # The original color should be (30, 215, 96), however, depending on
  # (the quality of) your LED stripe, you may need to do adjustments.
  spotify_color: (30, 255, 10)
  loading_color: (25,189,255)  # displayed when loading an album
  seeking_color: (255, 100, 0)  # displayed when connecting to audio device
